/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ExamType {
  FA1 = 'FA1',
  SA1 = 'SA1',
  FA2 = 'FA2',
  SA2 = 'SA2'
}
export const enum Subject {
  English = 'English',
  Hindi = 'Hindi',
  Marathi = 'Marathi',
  SST = 'SST',
  Science = 'Science',
  Mathematics = 'Mathematics',
  Computer = 'Computer'
}
export declare function calculateTotalMarks(allSubjectMarks: Record<Subject, number>, excludeSubjects: Array<Subject>): number
export declare function calculateTotalMarksPerSubject(oralSubjectMarks: Record<Subject, number>, writtenSubjectMarks: Record<Subject, number>, excludeSubjects: Array<Subject>): Record<Subject, number>
export declare function calculateFaPercentage(faMarks: number, fullMarks: number): number
export declare function calculateSa1Percentage(sa1Marks: number, fullMarks: number, fa1Percentage: number): number
export declare function calculateSa2Percentage(sa2Marks: number, fullMarks: number, sa1Percentage: number): number
