/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ExamType {
  FA1 = 'FA1',
  SA1 = 'SA1',
  FA2 = 'FA2',
  SA2 = 'SA2'
}
export const enum Subject {
  English = 'English',
  Hindi = 'Hindi',
  Marathi = 'Marathi',
  Sst = 'Sst',
  Science = 'Science',
  Mathematics = 'Mathematics',
  Computer = 'Computer'
}
export declare function calculateTotalMarks(allSubjectMarks: Record<Subject, number>, excludeSubject: Array<Subject>): Promise<number>
